name: 中青看点2

on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
    - cron: '*/30 0-23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/pizile/CXK.git ~/CXK
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/CXK
          npm install
          npm install cron
          npm install request
      - name: '运行 【中青看点2】'
        run: |
          cd ~/CXK   
          node Task/youth2.js
