name: 中青阅读2

on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
     - cron: '0 1-22/3 * * *'
jobs:
  build:
    runs-on: ubuntu-16.04     
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/xiaokxiansheng/js.git ~/js
      - name: Use Node.js 14.15.4
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/js
          npm install
          npm install cron
          npm install request
          npm install single-line-log
      - name: '运行 【中青阅读2】'
        run: |
          cd ~/js   
          node Task/Youth_AutoRead2.js
